// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYdNkCtjwt6bpr66F85M50wPHnLIh3kiM',
    appId: '1:928571153651:web:ce64239622e9a201c0ab86',
    messagingSenderId: '928571153651',
    projectId: 'dualingocoran',
    authDomain: 'dualingocoran.firebaseapp.com',
    storageBucket: 'dualingocoran.firebasestorage.app',
    measurementId: 'G-T4K09CTKVE',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxDA_PcTNoDyae1QS6pKXIwsoyi4FZR0',
    appId: '1:928571153651:android:391623d3c9d8b9bdc0ab86',
    messagingSenderId: '928571153651',
    projectId: 'dualingocoran',
    storageBucket: 'dualingocoran.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimMnTAdIPjEcssq5TLm8wZ-lW7PvQKr4',
    appId: '1:928571153651:ios:9c404ab351079bdac0ab86',
    messagingSenderId: '928571153651',
    projectId: 'dualingocoran',
    storageBucket: 'dualingocoran.firebasestorage.app',
    iosBundleId: 'com.example.dualingocoran',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimMnTAdIPjEcssq5TLm8wZ-lW7PvQKr4',
    appId: '1:928571153651:ios:9c404ab351079bdac0ab86',
    messagingSenderId: '928571153651',
    projectId: 'dualingocoran',
    storageBucket: 'dualingocoran.firebasestorage.app',
    iosBundleId: 'com.example.dualingocoran',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYdNkCtjwt6bpr66F85M50wPHnLIh3kiM',
    appId: '1:928571153651:web:a18ec136e705e7bfc0ab86',
    messagingSenderId: '928571153651',
    projectId: 'dualingocoran',
    authDomain: 'dualingocoran.firebaseapp.com',
    storageBucket: 'dualingocoran.firebasestorage.app',
    measurementId: 'G-W9WQRNB9F1',
  );
}
