import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  
  AppLocalizations(this.locale);
  
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
  
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'DualingOcoran',
      'roadmap': 'Roadmap',
      'profile': 'Profile',
      'settings': 'Settings',
      'progression': 'Progression',
      'exercises': 'Exercises',
      'lessons': 'Lessons',
      'language': 'Language',
      'english': 'English',
      'french': 'French',
      'arabic': 'Arabic',
      'newWordsToLearn': 'New Words to Learn',
      'startLesson': 'Start Lesson',
      'description': 'Description',
      'example': 'Example',
      'noLessonsFound': 'No lessons found',
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'lesson': 'Lesson',
      'section': 'Section',
      'question': 'Question',
      'answer': 'Answer',
      'options': 'Options',
      'submit': 'Submit',
      'correct': 'Correct!',
      'incorrect': 'Incorrect!',
      'tryAgain': 'Try Again',
      'continue': 'Continue',
      'finish': 'Finish',
      'score': 'Score',
      'progress': 'Progress',
      'completed': 'Completed',
      'inProgress': 'In Progress',
      'notStarted': 'Not Started',
      'totalXP': 'Total XP',
      'currentStreak': 'Current Streak',
      'bestStreak': 'Best Streak',
      'accuracy': 'Accuracy',
      'lessonsCompleted': 'Lessons Completed',
      'totalLessons': 'Total Lessons',
      'lessonProgress': 'Lesson Progress',
      'badgesAndAchievements': 'Badges & Achievements',
      'detailedStats': 'Detailed Statistics',
      'totalStudyTime': 'Total Study Time',
      'exercisesCompleted': 'Exercises Completed',
      'wordsLearned': 'Words Learned',
      'studySessions': 'Study Sessions',
      'activeDays': 'Active Days',
      'firstStep': 'First Step',
      'streak7Days': '7 Day Streak',
      'accuracy80Plus': '80%+ Accuracy',
      'fiveLessons': '5 Lessons',
      'streak30Days': '30 Day Streak',
      'hundredPercentAccuracy': '100% Accuracy',
      'days': 'days',
      'percent': '%',
    },
    'fr': {
      'appTitle': 'DualingOcoran',
      'roadmap': 'Parcours',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'progression': 'Progression',
      'exercises': 'Exercices',
      'lessons': 'Leçons',
      'language': 'Langue',
      'english': 'Anglais',
      'french': 'Français',
      'arabic': 'Arabe',
      'newWordsToLearn': 'Nouveaux mots à apprendre',
      'startLesson': 'Commencer la leçon',
      'description': 'Description',
      'example': 'Exemple',
      'noLessonsFound': 'Aucune leçon trouvée',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'retry': 'Réessayer',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'lesson': 'Leçon',
      'section': 'Section',
      'question': 'Question',
      'answer': 'Réponse',
      'options': 'Options',
      'submit': 'Soumettre',
      'correct': 'Correct !',
      'incorrect': 'Incorrect !',
      'tryAgain': 'Réessayer',
      'continue': 'Continuer',
      'finish': 'Terminer',
      'score': 'Score',
      'progress': 'Progression',
      'completed': 'Terminé',
      'inProgress': 'En cours',
      'notStarted': 'Non commencé',
      'totalXP': 'XP Total',
      'currentStreak': 'Streak actuel',
      'bestStreak': 'Meilleur streak',
      'accuracy': 'Précision',
      'lessonsCompleted': 'Leçons terminées',
      'totalLessons': 'Total des leçons',
      'lessonProgress': 'Progression des leçons',
      'badgesAndAchievements': 'Badges & Accomplissements',
      'detailedStats': 'Statistiques détaillées',
      'totalStudyTime': 'Temps total d\'étude',
      'exercisesCompleted': 'Exercices complétés',
      'wordsLearned': 'Mots appris',
      'studySessions': 'Sessions d\'étude',
      'activeDays': 'Jours actifs',
      'firstStep': 'Premier Pas',
      'streak7Days': 'Streak 7 jours',
      'accuracy80Plus': 'Précision 80%+',
      'fiveLessons': '5 leçons',
      'streak30Days': 'Streak 30 jours',
      'hundredPercentAccuracy': '100% Précision',
      'days': 'jours',
      'percent': '%',
    },
    'ar': {
      'appTitle': 'دوالينغو كوران',
      'roadmap': 'الخريطة',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'progression': 'التقدم',
      'exercises': 'التمارين',
      'lessons': 'الدروس',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'newWordsToLearn': 'كلمات جديدة للتعلم',
      'startLesson': 'ابدأ الدرس',
      'description': 'الوصف',
      'example': 'مثال',
      'noLessonsFound': 'لم يتم العثور على دروس',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'lesson': 'الدرس',
      'section': 'القسم',
      'question': 'السؤال',
      'answer': 'الإجابة',
      'options': 'الخيارات',
      'submit': 'إرسال',
      'correct': 'صحيح!',
      'incorrect': 'خطأ!',
      'tryAgain': 'حاول مرة أخرى',
      'continue': 'متابعة',
      'finish': 'إنهاء',
      'score': 'النتيجة',
      'progress': 'التقدم',
      'completed': 'مكتمل',
      'inProgress': 'قيد التنفيذ',
      'notStarted': 'لم يبدأ',
      'totalXP': 'إكس بي الإجمالي',
      'currentStreak': 'الخط المتواصل الحالي',
      'bestStreak': 'أفضل خط متواصل',
      'accuracy': 'الدقة',
      'lessonsCompleted': 'الدروس المكتملة',
      'totalLessons': 'إجمالي الدروس',
      'lessonProgress': 'تقدم الدروس',
      'badgesAndAchievements': 'الشارات والإنجازات',
      'detailedStats': 'إحصائيات مفصلة',
      'totalStudyTime': 'إجمالي وقت الدراسة',
      'exercisesCompleted': 'التمارين المكتملة',
      'wordsLearned': 'الكلمات المكتسبة',
      'studySessions': 'جلسات الدراسة',
      'activeDays': 'الأيام النشطة',
      'firstStep': 'الخطوة الأولى',
      'streak7Days': 'خط متواصل 7 أيام',
      'accuracy80Plus': 'دقة 80%+',
      'fiveLessons': '5 دروس',
      'streak30Days': 'خط متواصل 30 يوم',
      'hundredPercentAccuracy': 'دقة 100%',
      'days': 'أيام',
      'percent': '%',
    },
  };
  
  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['en']![key] ?? 
           key;
  }
  
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('fr'),
    Locale('ar'),
  ];
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();
  
  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }
  
  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }
  
  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
